### PR TITLE
add /usr/local/etc/xdg to paths

### PR DESCRIPTION
**Pull request by mstuehn**
This patch enabled me to run jgmenu on FreeBSD.

### CODE REVIEW

**Comment by johanmalm** [comment]
Out of curiosity, what's your `$XDG_CONFIG_DIRS` set to?

**Comment by mstuehn** [comment]
echo $XDG_CONFIG_DIRS
/etc:/usr/local/etc/xdg:/usr/share:/usr/local/share

Hmm, it already contains /usr/local/etc/xdg which should make my patch completely nonsense. I do not have an explanation, sorry for the noise...

**Comment by johanmalm** [comment]
Is jgmenu running okay for you?
I'm happy to help track down any issue you've having.

**Comment by mstuehn** [comment]
Everything's working perfectly for me, thank you very much.

**Pull request merged**
