### PR TITLE
Add 2-color gradient for menu

### PR DESCRIPTION
**Pull request by Artideusz**

### CODE REVIEW

**Comment by johanmalm** [comment]
Thanks

**Comment by wsdfhjxc** [comment]
This seems to be a little bit of a breaking change. My menu doesn't have a solid background anymore, and I get a half-transparent gradient instead. And this is the only thing related to the menu background in my `jgmenurc` file:

```
color_menu_bg = #eff0f1 100
```

Am I missing something, or some fixups are needed?

**Comment by johanmalm** [comment]
Thanks. I’ve initialised color_menu_bg_gradient to disable gradient by default.
Do make clean ; make if you’re pulling in the same repo.
A few more fixes, coming.

**Comment by wsdfhjxc** [comment]
Unfortunately, after pulling in the recent commit, it's still the same. The last correct behavior is at commit 5f712b2ea4513c66c2c6c01eea9e666f5041f309.

**Comment by johanmalm** [comment]
Have you done a make clean in between. 
What color is the gradient?

**Comment by wsdfhjxc** [comment]
Yes, it's after doing a clean build and while directly running the compiled binary. Doing the same after checking out the mentioned commit (which precedes the commit that introduced gradients), makes the menu background solid again, as expected.

The gradient is from top to bottom, starting from the `color_menu_bg` at the top and going full transparent at the bottom (I can see through the bottom part of the menu). The effect is quite interesting, but I'd rather keep my menu background solid :smile:

**Pull request merged**
